liip_imagine:
    resolvers:
        default:
            web_path: ~
    
    filter_sets:
        product_thumbnail:
            quality: 80
            filters:
                thumbnail: { size: [300, 300], mode: outbound }