<?php

namespace ContainerJ2yNIRM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllercancelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.viNiFh5.App\Controller\OrderController::cancel()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.viNiFh5.App\\Controller\\OrderController::cancel()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'order' => ['privates', '.errored..service_locator.viNiFh5.App\\Entity\\Order', NULL, 'Cannot autowire service ".service_locator.viNiFh5": it needs an instance of "App\\Entity\\Order" but this type has been excluded in "config/services.yaml".'],
            'orderService' => ['privates', 'App\\Service\\OrderService', 'getOrderServiceService', true],
        ], [
            'order' => 'App\\Entity\\Order',
            'orderService' => 'App\\Service\\OrderService',
        ]))->withContext('App\\Controller\\OrderController::cancel()', $container);
    }
}
