<?php

namespace ContainerJ2yNIRM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllercheckoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aV.y5Ii.App\Controller\OrderController::checkout()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aV.y5Ii.App\\Controller\\OrderController::checkout()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderService' => ['privates', 'App\\Service\\OrderService', 'getOrderServiceService', true],
        ], [
            'orderService' => 'App\\Service\\OrderService',
        ]))->withContext('App\\Controller\\OrderController::checkout()', $container);
    }
}
