controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_verify_login:
    path: /verify-login
    controller: App\Controller\SecurityController::verifyLogin

app_verify_register:
    path: /verify-register
    controller: App\Controller\RegistrationController::verifyRegister