<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ2yNIRM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ2yNIRM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ2yNIRM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ2yNIRM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ2yNIRM\App_KernelDevDebugContainer([
    'container.build_hash' => 'J2yNIRM',
    'container.build_id' => '287a1656',
    'container.build_time' => 1747321047,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ2yNIRM');
