<?php

namespace ContainerPNpiCXC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LZFxcS9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lZFxcS9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lZFxcS9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.l_N54Qd.App\\Controller\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\CartController::add' => ['privates', '.service_locator.8eZNGup.App\\Controller\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\CartController::remove' => ['privates', '.service_locator.8eZNGup.App\\Controller\\CartController::remove()', 'getCartControllerremoveService', true],
            'App\\Controller\\CartController::clear' => ['privates', '.service_locator.l_N54Qd.App\\Controller\\CartController::clear()', 'getCartControllerclearService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.MTCWnA5.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\CategoryController::new()', 'getCategoryControllernewService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.ZAUGEyP.App\\Controller\\CategoryController::show()', 'getCategoryControllershowService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.gADJ5td.App\\Controller\\CategoryController::edit()', 'getCategoryControllereditService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.gADJ5td.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\OrderController::checkout' => ['privates', '.service_locator.aV.y5Ii.App\\Controller\\OrderController::checkout()', 'getOrderControllercheckoutService', true],
            'App\\Controller\\OrderController::show' => ['privates', '.service_locator.KyJldkg.App\\Controller\\OrderController::show()', 'getOrderControllershowService', true],
            'App\\Controller\\OrderController::index' => ['privates', '.service_locator.W3vCgFu.App\\Controller\\OrderController::index()', 'getOrderControllerindexService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\ProductController::new()', 'getProductControllernewService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.MFPVaGP.App\\Controller\\ProductController::edit()', 'getProductControllereditService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.MFPVaGP.App\\Controller\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator._Uqcq8q.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController::verifyLogin' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\SecurityController::verifyLogin()', 'getSecurityControllerverifyLoginService', true],
            'App\\Controller\\VerificationController::index' => ['privates', '.service_locator.egipcEH.App\\Controller\\VerificationController::index()', 'getVerificationControllerindexService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.l_N54Qd.App\\Controller\\CartController::index()', 'getCartControllerindexService', true],
            'App\\Controller\\CartController:add' => ['privates', '.service_locator.8eZNGup.App\\Controller\\CartController::add()', 'getCartControlleraddService', true],
            'App\\Controller\\CartController:remove' => ['privates', '.service_locator.8eZNGup.App\\Controller\\CartController::remove()', 'getCartControllerremoveService', true],
            'App\\Controller\\CartController:clear' => ['privates', '.service_locator.l_N54Qd.App\\Controller\\CartController::clear()', 'getCartControllerclearService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.MTCWnA5.App\\Controller\\CategoryController::index()', 'getCategoryControllerindexService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\CategoryController::new()', 'getCategoryControllernewService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.ZAUGEyP.App\\Controller\\CategoryController::show()', 'getCategoryControllershowService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.gADJ5td.App\\Controller\\CategoryController::edit()', 'getCategoryControllereditService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.gADJ5td.App\\Controller\\CategoryController::delete()', 'getCategoryControllerdeleteService', true],
            'App\\Controller\\OrderController:checkout' => ['privates', '.service_locator.aV.y5Ii.App\\Controller\\OrderController::checkout()', 'getOrderControllercheckoutService', true],
            'App\\Controller\\OrderController:show' => ['privates', '.service_locator.KyJldkg.App\\Controller\\OrderController::show()', 'getOrderControllershowService', true],
            'App\\Controller\\OrderController:index' => ['privates', '.service_locator.W3vCgFu.App\\Controller\\OrderController::index()', 'getOrderControllerindexService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\ProductController::new()', 'getProductControllernewService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.GwIh.sb.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.MFPVaGP.App\\Controller\\ProductController::edit()', 'getProductControllereditService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.MFPVaGP.App\\Controller\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator._Uqcq8q.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController:verifyLogin' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\SecurityController::verifyLogin()', 'getSecurityControllerverifyLoginService', true],
            'App\\Controller\\VerificationController:index' => ['privates', '.service_locator.egipcEH.App\\Controller\\VerificationController::index()', 'getVerificationControllerindexService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::add' => '?',
            'App\\Controller\\CartController::remove' => '?',
            'App\\Controller\\CartController::clear' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\OrderController::checkout' => '?',
            'App\\Controller\\OrderController::show' => '?',
            'App\\Controller\\OrderController::index' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::verifyLogin' => '?',
            'App\\Controller\\VerificationController::index' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:add' => '?',
            'App\\Controller\\CartController:remove' => '?',
            'App\\Controller\\CartController:clear' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\OrderController:checkout' => '?',
            'App\\Controller\\OrderController:show' => '?',
            'App\\Controller\\OrderController:index' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:verifyLogin' => '?',
            'App\\Controller\\VerificationController:index' => '?',
        ]);
    }
}
